### ISSUE TITLE
compilation fails

### ISSUE THREAD

**Issue by ruslansennov** [vavr-io/vavr-gwt-example#3]
```
[INFO] GET /recompile/VavrExample
[INFO]    Job VavrExample_1_0
[INFO]       starting job: VavrExample_1_0
[INFO]       binding: user.agent=safari
[INFO]       Compiling module VavrExample
[INFO]          Ignored 9 units with compilation errors in first pass.
[INFO] Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
[INFO]          [ERROR] Errors in 'jar:file:/home/ruslan/.m2/repository/io/vavr/vavr/0.9.0/vavr-0.9.0-sources.jar!/io/vavr/collection/JavaConverters.java'
[INFO]             [ERROR] Line 90: The type JavaConverters.ListView<T,C> must implement the inherited abstract method Collection<T>.toArray(T[])
[INFO]          Tracing compile failure path for type 'io.vavr.collection.JavaConverters'
[INFO]             [ERROR] Errors in 'jar:file:/home/ruslan/.m2/repository/io/vavr/vavr/0.9.0/vavr-0.9.0-sources.jar!/io/vavr/collection/JavaConverters.java'
[INFO]                [ERROR] Line 90: The type JavaConverters.ListView<T,C> must implement the inherited abstract method Collection<T>.toArray(T[])
```

`Seq.asJava*(*)` was added after last successful checking.
It seems `vavr-gwt` is broken... again.

**Comment by danieldietrich** [comment]
Mmhh, why did it not fail earlier? We should have seen it already after pulling the JavaConverters PR...

**Comment by ruslansennov** [comment]
Maybe the junit tests is not the same as real browser tests? I don't know, it needs to be investigated.

**Comment by danieldietrich** [comment]
Ok, thanks. Maybe [BrowserStack](https://www.browserstack.com/automate) is a solution (but haven't tried it...)

**Comment by nfekete** [comment]
Does it fail the build when this happens? Or it just reports it on the console but the build passes? I think there is a setting for that if that's the problem.

**Comment by ruslansennov** [comment]
@nfekete it fails after fetching `http://localhost:8888/VavrExample/index.html`. Please see vavr-io/vavr#1992

**Comment by nfekete** [comment]
I saw that PR, but my question was: does it fail the build as it should (and you get a notification about it so you can act on it) or it will fail later at runtime?

**Comment by ruslansennov** [comment]
I tried to add `-strict` flag to `pom.xml` in `vavr-gwt` module (with `<failOnError>true</failOnError>` in `gwt-maven-plugin` configuration), but it not stops the build. Setting `logLevel` to `DEBUG` shows the problem units but doesn't anything. It seems we can get a notification in real browser only. It seems there is only one right way: make tests coverage ratio better

**Comment by ruslansennov** [comment]
> make tests coverage ratio better

But I have no idea how we can automatically check new methods that will be added to `vavr` in the future.

> I think there is a setting for that if that's the problem.

Let me know if you will find them, thanks

**Comment by nfekete** [comment]
> with `<failOnError>true</failOnError>` in gwt-maven-plugin configuration

Did you try to put that into the `vavr-gwt-example` `pom.xml` or into `vavr-gwt`. You should put it into `vavr-gwt-example` as the `vavr-gwt` project doesn't involve GWT compilation, only packaging.

**Comment by ruslansennov** [comment]
> the vavr-gwt project doesn't involve GWT compilation, only packaging.

Sorry, what do you mean? Every build of `vavr-gwt` module runs the unit tests and compiles sources of `vavr-gwt` and `vavr`

**Comment by nfekete** [comment]
Ah, I see. I thought you're using just the Thomas Broyer's gwt plugin with `gwt-lib` module type and that's it.

**Comment by ruslansennov** [comment]
fixed in last release
